import React, { useState, useEffect } from 'react';
import { ClipboardList, Copy, Check, ChevronDown, ChevronUp, Save } from 'lucide-react';
import { db } from '../firebase';
import {
  collection, onSnapshot, query, doc, setDoc, getDoc
} from 'firebase/firestore';
import { useFirebase } from '../FirebaseProvider';
import { Pet, SitterHandoff } from '../types';

const EMPTY_FORM: Omit<SitterHandoff, 'id' | 'petId' | 'createdAt'> = {
  sitterName: '',
  feedingInstructions: '',
  medications: '',
  vetName: '',
  vetPhone: '',
  emergencyContact: '',
  behaviourNotes: '',
  routineNotes: '',
};

export default function SitterHandoffSheet() {
  const { user } = useFirebase();
  const [pets, setPets] = useState<Pet[]>([]);
  const [selectedPetId, setSelectedPetId] = useState('');
  const [form, setForm] = useState(EMPTY_FORM);
  const [saved, setSaved] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showPreview, setShowPreview] = useState(false);

  const selectedPet = pets.find(p => p.id === selectedPetId);

  useEffect(() => {
    if (!user) return;
    const q = query(collection(db, 'users', user.uid, 'pets'));
    return onSnapshot(q, snap => {
      const list = snap.docs.map(d => ({ id: d.id, ...d.data() })) as Pet[];
      setPets(list);
      if (list.length && !selectedPetId) setSelectedPetId(list[0].id);
    });
  }, [user]);

  useEffect(() => {
    if (!user || !selectedPetId) return;
    getDoc(doc(db, 'users', user.uid, 'sitterHandoffs', selectedPetId)).then(d => {
      if (d.exists()) {
        const data = d.data() as SitterHandoff;
        setForm({
          sitterName: data.sitterName ?? '',
          feedingInstructions: data.feedingInstructions,
          medications: data.medications,
          vetName: data.vetName,
          vetPhone: data.vetPhone,
          emergencyContact: data.emergencyContact,
          behaviourNotes: data.behaviourNotes,
          routineNotes: data.routineNotes,
        });
      } else {
        setForm(EMPTY_FORM);
      }
    });
  }, [user, selectedPetId]);

  const handleSave = async () => {
    if (!user || !selectedPetId) return;
    await setDoc(doc(db, 'users', user.uid, 'sitterHandoffs', selectedPetId), {
      petId: selectedPetId,
      ...form,
      createdAt: new Date().toISOString(),
    });
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  const generateText = () => {
    if (!selectedPet) return '';
    return `🐾 PAWESOME SITTER SHEET — ${selectedPet.name.toUpperCase()}
${'─'.repeat(40)}
Pet: ${selectedPet.name} · ${selectedPet.breed} ${selectedPet.species} · ${selectedPet.age} yr${selectedPet.age !== 1 ? 's' : ''}
${form.sitterName ? `Sitter: ${form.sitterName}` : ''}

🍽 FEEDING
${form.feedingInstructions || 'See owner for instructions.'}

💊 MEDICATIONS
${form.medications || 'None.'}

🏥 VET
${form.vetName || '—'} · ${form.vetPhone || '—'}

📞 EMERGENCY CONTACT
${form.emergencyContact || '—'}

🐶 BEHAVIOUR NOTES
${form.behaviourNotes || 'None.'}

📅 DAILY ROUTINE
${form.routineNotes || 'None.'}

Generated by Pawesome 🐾`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const field = (label: string, key: keyof typeof form, placeholder: string, rows = 2) => (
    <div>
      <label className="text-xs font-semibold text-[#A19B95] uppercase tracking-wide">{label}</label>
      <textarea
        value={form[key] as string}
        onChange={e => setForm(f => ({ ...f, [key]: e.target.value }))}
        placeholder={placeholder}
        rows={rows}
        className="mt-1 w-full border border-[#F0EBE6] rounded-xl px-3 py-2 text-sm resize-none focus:outline-none focus:ring-2 focus:ring-[#5A5A40]/20"
      />
    </div>
  );

  return (
    <div className="max-w-2xl mx-auto p-4 space-y-6">
      <div>
        <h2 className="font-serif text-2xl font-bold text-[#1A1A1A]">Sitter Handoff Sheet</h2>
        <p className="text-[#A19B95] text-sm mt-0.5">Fill once, copy and send every time you travel.</p>
      </div>

      {pets.length > 1 && (
        <div className="flex gap-2 flex-wrap">
          {pets.map(p => (
            <button key={p.id} onClick={() => setSelectedPetId(p.id)}
              className={`px-4 py-2 rounded-xl text-sm font-semibold transition-colors ${selectedPetId === p.id ? 'bg-[#5A5A40] text-white' : 'bg-[#F5F0EB] text-[#5A5A40] hover:bg-[#EDE8E3]'}`}>
              {p.name}
            </button>
          ))}
        </div>
      )}

      {selectedPet && (
        <>
          <div className="bg-white rounded-3xl border border-[#F0EBE6] p-5 space-y-4">
            <div>
              <label className="text-xs font-semibold text-[#A19B95] uppercase tracking-wide">Sitter's name (optional)</label>
              <input value={form.sitterName} onChange={e => setForm(f => ({ ...f, sitterName: e.target.value }))} placeholder="e.g. Sarah" className="mt-1 w-full border border-[#F0EBE6] rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#5A5A40]/20" />
            </div>
            {field('Feeding instructions', 'feedingInstructions', 'e.g. 1 cup dry food at 8am and 6pm. Loves a treat after dinner.', 3)}
            {field('Medications', 'medications', 'e.g. Half a Metacam tablet with morning food. None if vomiting.')}
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-xs font-semibold text-[#A19B95] uppercase tracking-wide">Vet name</label>
                <input value={form.vetName} onChange={e => setForm(f => ({ ...f, vetName: e.target.value }))} placeholder="Dr. Smith" className="mt-1 w-full border border-[#F0EBE6] rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#5A5A40]/20" />
              </div>
              <div>
                <label className="text-xs font-semibold text-[#A19B95] uppercase tracking-wide">Vet phone</label>
                <input value={form.vetPhone} onChange={e => setForm(f => ({ ...f, vetPhone: e.target.value }))} placeholder="01234 567890" className="mt-1 w-full border border-[#F0EBE6] rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#5A5A40]/20" />
              </div>
            </div>
            {field('Emergency contact', 'emergencyContact', 'e.g. Mum — 07700 900123', 1)}
            {field('Behaviour notes', 'behaviourNotes', "e.g. Scared of the hoover. Friendly with other dogs. Doesn't like strangers picking him up.", 3)}
            {field('Daily routine', 'routineNotes', 'e.g. Walk at 8am and 5pm (20 min each). Nap after lunch. Bedtime at 10pm in his crate.', 3)}
          </div>

          <div className="flex gap-3">
            <button onClick={handleSave} className="flex items-center gap-2 bg-[#5A5A40] text-white px-5 py-2.5 rounded-2xl text-sm font-bold hover:bg-[#4A4A33] transition-colors">
              {saved ? <Check size={16} /> : <Save size={16} />}
              {saved ? 'Saved!' : 'Save'}
            </button>
            <button onClick={() => setShowPreview(!showPreview)} className="flex items-center gap-2 border border-[#F0EBE6] text-[#5A5A40] px-5 py-2.5 rounded-2xl text-sm font-bold hover:bg-[#F5F0EB] transition-colors">
              <ClipboardList size={16} />
              Preview
              {showPreview ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
            </button>
            <button onClick={handleCopy} className="flex items-center gap-2 border border-[#F0EBE6] text-[#5A5A40] px-5 py-2.5 rounded-2xl text-sm font-bold hover:bg-[#F5F0EB] transition-colors ml-auto">
              {copied ? <Check size={16} /> : <Copy size={16} />}
              {copied ? 'Copied!' : 'Copy'}
            </button>
          </div>

          {showPreview && (
            <div className="bg-[#FDFCFB] border border-[#F0EBE6] rounded-2xl p-5">
              <pre className="text-xs text-[#5A5A40] whitespace-pre-wrap font-mono leading-relaxed">{generateText()}</pre>
            </div>
          )}
        </>
      )}

      {pets.length === 0 && (
        <div className="bg-white rounded-3xl border border-[#F0EBE6] p-10 text-center">
          <ClipboardList size={32} className="text-[#D4CFC9] mx-auto mb-3" />
          <p className="text-[#A19B95] text-sm">Add a pet profile first to create a handoff sheet.</p>
        </div>
      )}
    </div>
  );
}
